name: Analyze Excel Data

on:
  workflow_dispatch:   # Cho phép bạn chạy thủ công

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Run analyze script
        run: python analyze_excel.py
